" TODO Add tag search and gitignore tag indexing

" ---------- GUI ----------
set guifont=Monaco:h14
colorscheme molokai
set colorcolumn=78
set mouse=a

" Syntax highlighting
syntax enable

" Replace tab with arrow
" Replace eol with not
set list
set listchars=tab:▸\ ,eol:¬

set foldmethod=indent
set foldlevelstart=20

" Pipe cursor for insert mode in vi.
let &t_SI = "\<Esc>]50;CursorShape=1\x7"
let &t_EI = "\<Esc>]50;CursorShape=0\x7"

" Cancel command-t search using esc.
let g:CommandTCancelMap=['<ESC>']

" Reload file when updated.
set autoread

" ---------- KEY BINDINGS ----------
let mapleader = "\<space>"

" Easymotion navigation
let g:EasyMotion_leader_key = '<Leader>'
let g:EasyMotion_mapping_t = '' " Unused mapping competing with Command-t
let g:EasyMotion_mapping_T = '' " Unused mapping competing with Command-t

nmap <leader>cp :let @* = expand("%:p")<CR>

function! ClearTrailingSpace()
  let lineNumber = line(".")
  %s/\ *$//g "\<CR>"
  let @/ = "" "\<CR>"
  exe ":" lineNumber
endfunction
nmap <leader>ds :call ClearTrailingSpace()<CR>

map <C-l> :bnext<CR>
map <C-h> :bprev<CR>

" ---------- OTHER ----------
set backspace=2               " Make backspace work normally in insert mode
set smartcase                 " Ignore case if search is lower-case
set hlsearch                  " Highlight search terms
set incsearch                 " Show search matches as you type
set number                    " Show line numbers
set rnu                       " Relative line numbers
set tabstop=2                 " Add to space tabs
set nowrap                    " Turn of word-wrap
set shiftwidth=2
set expandtab
set autoindent
set history=1000
set undolevels=1000
set wildignore=*.swp
set title
set visualbell
set noerrorbells
set nobackup
set noswapfile
set hidden                   " Allow buffer switching without saving file

filetype plugin indent on     " Load indent files to automatically do language-dependent indenting

" ---------- PATHOGEN INSTALL ----------
call pathogen#infect()
call pathogen#helptags()
