" TODO Add filepath copy key binding.
" TODO Add kill whitespace: command! KillWhitespace :normal :%s/ *$//g<cr><c-o><cr>

" ---------- GUI ----------
set guifont=Monaco:h14
colorscheme molokai
set colorcolumn=78
set mouse=a

" Syntax highlighting
syntax enable

" Replace tab with arrow
" Replace eol with not
set list
set listchars=tab:▸\ ,eol:¬

" Pipe cursor for insert mode in vi.
let &t_SI = "\<Esc>]50;CursorShape=1\x7"
let &t_EI = "\<Esc>]50;CursorShape=0\x7"

" Cancel command-t search using esc.
" let g:CommandTCancelMap=['<ESC>']

" Resize windows depending on context
set winwidth=84
set winheight=5
set winminheight=5
set winheight=999

" Reload file when updated.
set autoread

" ---------- KEY BINDINGS ----------
let mapleader = "\<space>"

" Rails shortcuts for models/views/controllers/helpers
map <leader>gv :CommandTFlush<cr>\|:CommandT app/views<cr>
map <leader>gc :CommandTFlush<cr>\|:CommandT app/controllers<cr>
map <leader>gm :CommandTFlush<cr>\|:CommandT app/models<cr>
map <leader>gh :CommandTFlush<cr>\|:CommandT app/helpers<cr>

" Rails shortcut for Gemfile
map <leader>gg :topleft 16 :split Gemfile<cr>

map <C-l> :bnext<CR>
map <C-h> :bprev<CR>

" ---------- OTHER ----------
set backspace=2               " Make backspace work normally in insert mode
set smartcase                 " Ignore case if search is lower-case
set hlsearch                  " Highlight search terms
set incsearch                 " Show search matches as you type
set number                    " Show line numbers
set rnu                       " Relative line numbers
set tabstop=2                 " Add to space tabs
set nowrap                    " Turn of word-wrap
set shiftwidth=2
set expandtab
set autoindent
set history=1000
set undolevels=1000
set wildignore=*.swp
set title
set visualbell
set noerrorbells
set nobackup
set noswapfile
" TODO switch Netrw with NerdTree
"set hidden                   " Allow buffer switching without saving file

filetype plugin indent on     " Load indent files to automatically do language-dependent indenting

" ---------- PATHOGEN INSTALL ----------
call pathogen#infect()
call pathogen#helptags()
